//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBFoodRecipesEntities : DbContext
    {
        public DBFoodRecipesEntities()
            : base("name=DBFoodRecipesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FavoriteFood> FavoriteFoods { get; set; }
        public virtual DbSet<FoodCookingStep> FoodCookingSteps { get; set; }
        public virtual DbSet<FoodRecipe> FoodRecipes { get; set; }
    
        [DbFunction("DBFoodRecipesEntities", "FullTextSearchNameFood")]
        public virtual IQueryable<FullTextSearchNameFood_Result> FullTextSearchNameFood(string nameFood)
        {
            var nameFoodParameter = nameFood != null ?
                new ObjectParameter("nameFood", nameFood) :
                new ObjectParameter("nameFood", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FullTextSearchNameFood_Result>("[DBFoodRecipesEntities].[FullTextSearchNameFood](@nameFood)", nameFoodParameter);
        }
    }
}
