//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBFoodRecipesEntities : DbContext
    {
        public DBFoodRecipesEntities()
            : base("name=DBFoodRecipesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FavoriteFood> FavoriteFoods { get; set; }
        public virtual DbSet<FoodCookingStep> FoodCookingSteps { get; set; }
        public virtual DbSet<FoodRecipe> FoodRecipes { get; set; }
    }
}
