//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCookingStep
    {
        public int IdFoodRecipes { get; set; }
        public int NumberStep { get; set; }
        public string Step { get; set; }
        public string ImageStep { get; set; }
    
        public virtual FoodRecipe FoodRecipe { get; set; }
    }
}
